name: Shards
version: 2.0.9
api-version: 1.13
main: com.zeltuv.shards.ShardPlugin
softdepend: [PlaceholderAPI,WorldGuard]
libraries:
  - "org.apache.commons:commons-lang3:3.12.0"
  - "com.zaxxer:HikariCP:5.0.1"
  - "com.mysql:mysql-connector-j:8.0.33"
  - 'com.google.code.gson:gson:2.10.1'
  - 'org.xerial:sqlite-jdbc:3.42.0.0'
